name: Android Build

on:
  workflow_dispatch: # 支持手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android 34
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools-version: 34.0.0

      - name: Set JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 动态获取构建工具版本
      - name: Get build tools versions
        id: versions
        run: |
          NDK_VERSION=$(grep "ndkVersion" app/build.gradle | awk -F"'" '{print $2}')
          echo "NDK_VERSION=$NDK_VERSION" >> $GITHUB_OUTPUT
          
          CMAKE_VERSION=$(grep -A5 'externalNativeBuild' app/build.gradle | grep 'version' | awk -F"'" '{print $2}')
          echo "CMAKE_VERSION=${CMAKE_VERSION//+/}" >> $GITHUB_OUTPUT  # 移除+号

      # 安装精确版本工具
      - name: Install NDK & CMake
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager \
            "ndk;${{ steps.versions.outputs.NDK_VERSION }}" \
            "cmake;${{ steps.versions.outputs.CMAKE_VERSION }}"

      # 优化缓存配置
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.android/build-cache
            ~/.kotlin/cache
            ~/.hilt
            .ccache
          key: android-build-${{ hashFiles('**/build.gradle', '**/gradle.properties') }}

      # Hilt依赖需要https协议
      - name: Add google repository
        run: sed -i 's/maven { url /maven { url "https:/' settings.gradle

      # 接受所有许可证
      - name: Accept licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      # 使用守护进程提升构建速度
      - name: Build APK
        env:
          CCACHE_DIR: "${{ github.workspace }}/.ccache"
          CCACHE_COMPRESS: true
        run: |
          ./gradlew assembleRelease \
            --no-daemon \
            --parallel \
            --build-cache \
            -Pkotlin.compiler.execution.strategy=in-process \
            -x lint

      # 上传构建结果
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            app/build/outputs/apk/**/*.apk
          retention-days: 7
